import { videoType,commentType } from '~types/type'
import poster from "~assets/poster/poster.jpg"
import poster2 from "~assets/poster/poster2.jpeg"
import avatar from "~assets/avatar.png"
const videoList:videoType[]=[
    {
        url:"",
        poster:poster,
        name:"神的萝莉摇",
        id:"1",
        userId:"111",
        stared:13,
        liked:28,
        comments:[
            {
                id:"1",
                userId:"111",
                avatar:avatar,
                content:"like😍"
            }   
        ]
    },
    {
        url:"",
        poster:poster2,
        name:"奶茶昔好喝",
        id:"2",
        userId:"111",
        stared:13,
        liked:28,
        comments:[
            {
                id:"1",
                userId:"111",
                avatar:avatar,
                content:"like😍"
            }   
        ]
    },
    {
        url:"",
        poster:poster,
        name:"神的萝莉摇",
        id:"3",
        userId:"111",
        stared:13,
        liked:28,
        comments:[
            {
                id:"1",
                userId:"111",
                avatar:avatar,
                content:"like😍"
            }   
        ]
    },
    {
        url:"",
        poster:poster2,
        name:"奶茶昔好喝",
        id:"4",
        userId:"111",
        stared:13,
        liked:28,
        comments:[
            {
                id:"1",
                userId:"111",
                avatar:avatar,
                content:"like😍"
            }   
        ]
    },
    {
        url:"",
        poster:poster,
        name:"神的萝莉摇",
        id:"5",
        userId:"111",
        stared:13,
        liked:28,
        comments:[
            {
                id:"1",
                userId:"111",
                avatar:avatar,
                content:"like😍"
            }   
        ]
    },
    {
        url:"",
        poster:poster2,
        name:"奶茶昔好喝",
        id:"6",
        userId:"111",
        stared:13,
        liked:28,
        comments:[
            {
                id:"1",
                userId:"111",
                avatar:avatar,
                content:"like😍"
            }   
        ]
    },
    {
        url:"",
        poster:poster,
        name:"神的萝莉摇",
        id:"7",
        userId:"111",
        stared:13,
        liked:28,
        comments:[
            {
                id:"1",
                userId:"111",
                avatar:avatar,
                content:"like😍"
            }   
        ]
    },
    {
        url:"",
        poster:poster2,
        name:"奶茶昔好喝",
        id:"8",
        userId:"111",
        stared:13,
        liked:28,
        comments:[
            {
                id:"1",
                userId:"111",
                avatar:avatar,
                content:"like😍"
            }   
        ]
    },
]
export default videoList